version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=sasa
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - my-network

  book-store-api:
    build:
      dockerfile: ./API.Dockerfile
    container_name: book-store-api
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: book-store-api
    depends_on:
      - redis
    restart: always
    networks:
      - my-network

  ngix:
    build:
      dockerfile: ./ngix.Dockerfile
    container_name: ngix
    restart: always
    ports:
      - 80:80
    depends_on:
      - book-store-api
networks:
  my-network:
    driver: bridge
